server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka
